name: Pipeline CI TechMarket Orders

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Ejecutar pruebas reutilizables
    uses: ./.github/workflows/template_test.yml

  build:
    name: Construir imagen Docker reutilizable
    needs: test
    uses: ./.github/workflows/template_build.yml
    with:
      image_name: techmarket-orders
      image_tag: ${{ github.sha }}