name: Pipeline CI TechMarket Orders

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Ejecutar pruebas reutilizables
    uses: ./.github/workflows/template_test.yml

  build:
    name: Build y push Docker a ECR
    needs: test
    uses: ./.github/workflows/template_build.yml
    with:
      ecr_repository: techmarket-orders
      image_tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}