name: Template Test

on:
  workflow_call:

jobs:
  test:
    name: Test microservicio Orders
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        working-directory: app
        run: npm install

      - name: Ejecutar pruebas
        working-directory: app
        run: npm test